apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app: netology-web  
  ports:
  - name: http
    port: 80            
    targetPort: 8080   
    protocol: TCP
  type: ClusterIP       
